### PR TITLE
[MARTIFACT-44] Integration test Handle maven-shade-plugin useDependencyReducedPomInJar

### PR DESCRIPTION
**Pull request by nielsbasjes**
In https://issues.apache.org/jira/browse/MARTIFACT-44 @hboutemy asked for a reproduction of the issue.

What better way to provide a reproduction than a new test for the project itself.
So this is ONLY an integration test that creates and installs a dependency which is then used, shaded, minimized and the reduced pom is then injected into the jar file.

So this pull request will FAIL the build because it does not solve the problem I ran into, only show it and facilitate reproduction by others.

During the install of the `include-drp` integration test you see (simplified for readability):
```
[INFO] --- maven-install-plugin:2.4:install (default-install) @ include-drp ---
[INFO] Installing include-drp-1.0-SNAPSHOT.jar to ~/.m2/.../include-drp-1.0-SNAPSHOT.jar
[INFO] Installing dependency-reduced-pom.xml to ~/.m2/.../include-drp-1.0-SNAPSHOT.pom
```
Then after a rebuild without install you run the `artifact:compare` and you get (simplified for readability):
```
[INFO] --- maven-artifact-plugin:3.4.0:compare (default-cli) @ include-drp ---
...
[ERROR] size mismatch include-drp-1.0-SNAPSHOT.pom: investigate with diffoscope target/reference/include-drp-1.0-SNAPSHOT.pom pom.xml
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

Closer inspection shows `dependency-reduced-pom.xml`, the pom.xml IN the second build of the jar and the `target/reference/include-drp-1.0-SNAPSHOT.pom` to be the same (so the build IS reproducible!).
Yet both are very different from the `pom.xml` against which the compare is done which fails the build.

### CODE REVIEW

**Comment by nielsbasjes** [comment]
Remarkable observation.

If I do `mvn clean verify artifact:compare` in the `include-drp` project I get this output and the build does not fail.

```
[INFO] --- maven-artifact-plugin:3.4.0:compare (default-cli) @ include-drp ---
[WARNING] SCM source tag in buildinfo source.scm.tag=maven-buildinfo-plugin does not permit rebuilders reproducible source checkout
[INFO] Saved info on build to /home/nbasjes/workspace/Apache/maven-artifact-plugin/src/it/include-drp/target/include-drp-1.0-SNAPSHOT.buildinfo
[INFO] Checking against reference build from central...
[INFO] Reference buildinfo file not found: it will be generated from downloaded reference artifacts
[INFO] Reference build java.version: 17 (from MANIFEST.MF Build-Jdk-Spec)
[INFO] Reference build os.name: Unix (from pom.properties newline)
[INFO] Minimal buildinfo generated from downloaded artifacts: /home/nbasjes/workspace/Apache/maven-artifact-plugin/src/it/include-drp/target/reference/include-drp-1.0-SNAPSHOT.buildinfo
[INFO] Reproducible Build output summary: 2 files ok
[INFO] Reproducible Build output comparison saved to /home/nbasjes/workspace/Apache/maven-artifact-plugin/src/it/include-drp/target/include-drp-1.0-SNAPSHOT.buildcompare
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

The mentioned buildinfo files now contain the same `length` and `checksums` for both
```
outputs.0.filename=include-drp-1.0-SNAPSHOT.pom
outputs.1.filename=include-drp-1.0-SNAPSHOT.jar
```

**Comment by nielsbasjes** [comment]
As it turns out the `clean verify artifact:compare` must be combined in a single invocation.
So my bug report was incorrect.

@hboutemy 
I'm leaving it up to you to either include this as an extra test to prove this is the way it works or to simply not include this.

**Comment by bmarwell** [comment]
Thanks for your contribution! I will put this PR in the slack channel

**Comment by hboutemy** [comment]
I'll drop this new IT, because we already have 2 compare ITs showing what to do
but I wrote #20 to try to enhance documentation

**Comment by jira-importer** [comment]
Resolve #141

**Pull request closed without merging**
