### PR TITLE
[MARTIFACT-38] Show failure reason and fail build if a plugin is mark…

### PR DESCRIPTION
**Pull request by michael-o**
…ed as "fail"

### CODE REVIEW

**Review by hboutemy — CHANGES_REQUESTED** [review]
as explained in depth in https://issues.apache.org/jira/browse/MARTIFACT-38 , I think we need a property to disable the fail, but report a warn instead: at least user knows that he's looking for WARNs

**Comment by michael-o** [comment]
Added a property which should do what you expect. Maybe this should split at least into two issues...

**Review by hboutemy — APPROVED** [review]
LGTM

**Comment by michael-o** [comment]
I have tried this on a multimodule project. as expected it fails fast, first fauly module will kill the bulid:
```
PS C:\Entwicklung\Projekte\maven-doxia> git diff
diff --git a/doxia-modules/doxia-module-apt/pom.xml b/doxia-modules/doxia-module-apt/pom.xml
index 870a1b0f..45b6f5ff 100644
--- a/doxia-modules/doxia-module-apt/pom.xml
+++ b/doxia-modules/doxia-module-apt/pom.xml
@@ -81,4 +81,21 @@ under the License.
       <scope>test</scope>
     </dependency>
   </dependencies>
+
+<build>
+    <plugins>
+        <plugin>
+            <groupId>org.springframework.boot</groupId>
+            <artifactId>spring-boot-maven-plugin</artifactId>
+ <version>3.0.2</version>
+            <executions>
+                <execution>
+                    <goals>
+                        <goal>repackage</goal>
+                    </goals>
+                </execution>
+            </executions>
+        </plugin>
+    </plugins>
+</build>
 </project>
PS C:\Entwicklung\Projekte\maven-doxia> mvn org.apache.maven.plugins:maven-artifact-plugin:3.3.1-SNAPSHOT:check-buildplan
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Doxia                                                              [pom]
[INFO] Doxia :: Sink API                                                  [jar]
[INFO] Doxia :: Test Documents                                            [jar]
[INFO] Doxia :: Core                                                      [jar]
[INFO] Doxia :: Modules                                                   [pom]
[INFO] Doxia :: APT Module                                                [jar]
[INFO] Doxia :: FML Module                                                [jar]
[INFO] Doxia :: XDoc Module                                               [jar]
[INFO] Doxia :: XHTML5 Module                                             [jar]
[INFO] Doxia :: Markdown Module                                           [jar]
Downloading from lda-public: https://deblndw011x.ad001.siemens.net/nexus/content/groups/lda-public/org/codehaus/mojo/clirr-maven-plugin/maven-metadata.xml
[WARNING] Could not transfer metadata org.codehaus.mojo:clirr-maven-plugin/maven-metadata.xml from/to lda-public (https://deblndw011x.ad001.siemens.net/nexus/content/groups/lda-public/): authorization failed for https://deblndw011x.ad001.siemens.net/nexus/content/groups/lda-public/org/codehaus/mojo/clirr-maven-plugin/maven-metadata.xml, status: 403 Forbidden
[INFO]
[INFO] --------------------< org.apache.maven.doxia:doxia >--------------------
[INFO] Building Doxia 2.0.0-M5-SNAPSHOT                                  [1/10]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-artifact-plugin:3.3.1-SNAPSHOT:check-buildplan (default-cli) @ doxia ---
[INFO] no known issue with org.apache.maven.plugins:maven-enforcer-plugin:3.1.0
[INFO] no known issue with com.diffplug.spotless:spotless-maven-plugin:2.28.0
[INFO] no known issue with org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0
[INFO] no known issue with org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0 (>= 1.7.0)
[INFO] no known issue with org.apache.rat:apache-rat-plugin:0.15
[INFO] no known issue with org.eclipse.sisu:sisu-maven-plugin:0.3.5 (>= 0.3.4)
[INFO] no known issue with org.apache.maven.plugins:maven-site-plugin:3.12.1
[INFO] no known issue with org.apache.maven.plugins:maven-install-plugin:3.1.0
[INFO] no known issue with org.apache.maven.plugins:maven-deploy-plugin:2.8.2
[INFO]
[INFO] ---------------< org.apache.maven.doxia:doxia-sink-api >----------------
[INFO] Building Doxia :: Sink API 2.0.0-M5-SNAPSHOT                      [2/10]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-artifact-plugin:3.3.1-SNAPSHOT:check-buildplan (default-cli) @ doxia-sink-api ---
[INFO] no known issue with org.apache.maven.plugins:maven-enforcer-plugin:3.1.0
[INFO] no known issue with com.diffplug.spotless:spotless-maven-plugin:2.28.0
[INFO] no known issue with org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0
[INFO] no known issue with org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0 (>= 1.7.0)
[INFO] no known issue with org.apache.maven.plugins:maven-resources-plugin:3.3.0
[INFO] no known issue with org.apache.rat:apache-rat-plugin:0.15
[INFO] no known issue with org.apache.maven.plugins:maven-compiler-plugin:3.10.1
[INFO] no known issue with org.eclipse.sisu:sisu-maven-plugin:0.3.5 (>= 0.3.4)
[INFO] no known issue with org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7
[INFO] no known issue with org.apache.maven.plugins:maven-jar-plugin:3.3.0 (>= 3.2.0)
[INFO] no known issue with org.apache.maven.plugins:maven-site-plugin:3.12.1
[INFO] no known issue with org.apache.maven.plugins:maven-install-plugin:3.1.0
[INFO] no known issue with org.apache.maven.plugins:maven-deploy-plugin:2.8.2
[INFO]
[INFO] ---------------< org.apache.maven.doxia:doxia-test-docs >---------------
[INFO] Building Doxia :: Test Documents 2.0.0-M5-SNAPSHOT                [3/10]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-artifact-plugin:3.3.1-SNAPSHOT:check-buildplan (default-cli) @ doxia-test-docs ---
[INFO] no known issue with org.apache.maven.plugins:maven-enforcer-plugin:3.1.0
[INFO] no known issue with com.diffplug.spotless:spotless-maven-plugin:2.28.0
[INFO] no known issue with org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0
[INFO] no known issue with org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0 (>= 1.7.0)
[INFO] no known issue with org.apache.maven.plugins:maven-resources-plugin:3.3.0
[INFO] no known issue with org.apache.rat:apache-rat-plugin:0.15
[INFO] no known issue with org.apache.maven.plugins:maven-compiler-plugin:3.10.1
[INFO] no known issue with org.eclipse.sisu:sisu-maven-plugin:0.3.5 (>= 0.3.4)
[INFO] no known issue with org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7
[INFO] no known issue with org.apache.maven.plugins:maven-jar-plugin:3.3.0 (>= 3.2.0)
[INFO] no known issue with org.apache.maven.plugins:maven-site-plugin:3.12.1
[INFO] no known issue with org.apache.maven.plugins:maven-install-plugin:3.1.0
[INFO] no known issue with org.apache.maven.plugins:maven-deploy-plugin:2.8.2
[INFO]
[INFO] -----------------< org.apache.maven.doxia:doxia-core >------------------
[INFO] Building Doxia :: Core 2.0.0-M5-SNAPSHOT                          [4/10]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-artifact-plugin:3.3.1-SNAPSHOT:check-buildplan (default-cli) @ doxia-core ---
[INFO] no known issue with org.apache.maven.plugins:maven-enforcer-plugin:3.1.0
[INFO] no known issue with com.diffplug.spotless:spotless-maven-plugin:2.28.0
[INFO] no known issue with org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0
[INFO] no known issue with org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0 (>= 1.7.0)
[INFO] no known issue with org.apache.maven.plugins:maven-resources-plugin:3.3.0
[INFO] no known issue with org.apache.rat:apache-rat-plugin:0.15
[INFO] no known issue with org.apache.maven.plugins:maven-compiler-plugin:3.10.1
[INFO] no known issue with org.eclipse.sisu:sisu-maven-plugin:0.3.5 (>= 0.3.4)
[INFO] no known issue with org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7
[INFO] no known issue with org.apache.maven.plugins:maven-jar-plugin:3.3.0 (>= 3.2.0)
[INFO] no known issue with org.apache.maven.plugins:maven-site-plugin:3.12.1
[INFO] no known issue with org.apache.maven.plugins:maven-install-plugin:3.1.0
[INFO] no known issue with org.apache.maven.plugins:maven-deploy-plugin:2.8.2
[INFO]
[INFO] ----------------< org.apache.maven.doxia:doxia-modules >----------------
[INFO] Building Doxia :: Modules 2.0.0-M5-SNAPSHOT                       [5/10]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-artifact-plugin:3.3.1-SNAPSHOT:check-buildplan (default-cli) @ doxia-modules ---
[INFO] no known issue with org.apache.maven.plugins:maven-enforcer-plugin:3.1.0
[INFO] no known issue with com.diffplug.spotless:spotless-maven-plugin:2.28.0
[INFO] no known issue with org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0
[INFO] no known issue with org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0 (>= 1.7.0)
[INFO] no known issue with org.apache.rat:apache-rat-plugin:0.15
[INFO] no known issue with org.eclipse.sisu:sisu-maven-plugin:0.3.5 (>= 0.3.4)
[INFO] no known issue with org.apache.maven.plugins:maven-site-plugin:3.12.1
[INFO] no known issue with org.apache.maven.plugins:maven-install-plugin:3.1.0
[INFO] no known issue with org.apache.maven.plugins:maven-deploy-plugin:2.8.2
[INFO]
[INFO] --------------< org.apache.maven.doxia:doxia-module-apt >---------------
[INFO] Building Doxia :: APT Module 2.0.0-M5-SNAPSHOT                    [6/10]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-artifact-plugin:3.3.1-SNAPSHOT:check-buildplan (default-cli) @ doxia-module-apt ---
[INFO] no known issue with org.apache.maven.plugins:maven-enforcer-plugin:3.1.0
[INFO] no known issue with com.diffplug.spotless:spotless-maven-plugin:2.28.0
[INFO] no known issue with org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0
[INFO] no known issue with org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0 (>= 1.7.0)
[INFO] no known issue with org.apache.maven.plugins:maven-resources-plugin:3.3.0
[INFO] no known issue with org.apache.rat:apache-rat-plugin:0.15
[INFO] no known issue with org.apache.maven.plugins:maven-compiler-plugin:3.10.1
[INFO] no known issue with org.eclipse.sisu:sisu-maven-plugin:0.3.5 (>= 0.3.4)
[INFO] no known issue with org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7
[INFO] no known issue with org.apache.maven.plugins:maven-jar-plugin:3.3.0 (>= 3.2.0)
[INFO] no known issue with org.apache.maven.plugins:maven-site-plugin:3.12.1
[ERROR] plugin without solution org.springframework.boot:spring-boot-maven-plugin:3.0.2, see https://github.com/spring-projects/spring-boot/issues/21005
[INFO] no known issue with org.apache.maven.plugins:maven-install-plugin:3.1.0
[INFO] no known issue with org.apache.maven.plugins:maven-deploy-plugin:2.8.2
[INFO] current module pom.xml is C:\Entwicklung\Projekte\maven-doxia\doxia-modules\doxia-module-apt/pom.xml
[INFO]         parent pom.xml is C:\Entwicklung\Projekte\maven-doxia\doxia-modules/pom.xml
[INFO]         parent pom.xml is C:\Entwicklung\Projekte\maven-doxia/pom.xml
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Doxia 2.0.0-M5-SNAPSHOT:
[INFO]
[INFO] Doxia .............................................. SUCCESS [  1.066 s]
[INFO] Doxia :: Sink API .................................. SUCCESS [  0.096 s]
[INFO] Doxia :: Test Documents ............................ SUCCESS [  0.013 s]
[INFO] Doxia :: Core ...................................... SUCCESS [  0.012 s]
[INFO] Doxia :: Modules ................................... SUCCESS [  0.008 s]
[INFO] Doxia :: APT Module ................................ FAILURE [  0.025 s]
[INFO] Doxia :: FML Module ................................ SKIPPED
[INFO] Doxia :: XDoc Module ............................... SKIPPED
[INFO] Doxia :: XHTML5 Module ............................. SKIPPED
[INFO] Doxia :: Markdown Module ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.202 s
[INFO] Finished at: 2023-02-03T14:43:36+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-artifact-plugin:3.3.1-SNAPSHOT:check-buildplan (default-cli) on project doxia-module-apt: non-reproducible plugin or configuration found with fix available -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :doxia-module-apt
```

Let's try with `-fae`:
```
PS C:\Entwicklung\Projekte\maven-doxia> mvn org.apache.maven.plugins:maven-artifact-plugin:3.3.1-SNAPSHOT:check-buildplan -fae
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Doxia                                                              [pom]
[INFO] Doxia :: Sink API                                                  [jar]
[INFO] Doxia :: Test Documents                                            [jar]
[INFO] Doxia :: Core                                                      [jar]
[INFO] Doxia :: Modules                                                   [pom]
[INFO] Doxia :: APT Module                                                [jar]
[INFO] Doxia :: FML Module                                                [jar]
[INFO] Doxia :: XDoc Module                                               [jar]
[INFO] Doxia :: XHTML5 Module                                             [jar]
[INFO] Doxia :: Markdown Module                                           [jar]
Downloading from lda-public: https://deblndw011x.ad001.siemens.net/nexus/content/groups/lda-public/org/codehaus/mojo/clirr-maven-plugin/maven-metadata.xml
[WARNING] Could not transfer metadata org.codehaus.mojo:clirr-maven-plugin/maven-metadata.xml from/to lda-public (https://deblndw011x.ad001.siemens.net/nexus/content/groups/lda-public/): authorization failed for https://deblndw011x.ad001.siemens.net/nexus/content/groups/lda-public/org/codehaus/mojo/clirr-maven-plugin/maven-metadata.xml, status: 403 Forbidden
[INFO]
[INFO] --------------------< org.apache.maven.doxia:doxia >--------------------
[INFO] Building Doxia 2.0.0-M5-SNAPSHOT                                  [1/10]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-artifact-plugin:3.3.1-SNAPSHOT:check-buildplan (default-cli) @ doxia ---
[INFO] no known issue with org.apache.maven.plugins:maven-enforcer-plugin:3.1.0
[INFO] no known issue with com.diffplug.spotless:spotless-maven-plugin:2.28.0
[INFO] no known issue with org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0
[INFO] no known issue with org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0 (>= 1.7.0)
[INFO] no known issue with org.apache.rat:apache-rat-plugin:0.15
[INFO] no known issue with org.eclipse.sisu:sisu-maven-plugin:0.3.5 (>= 0.3.4)
[INFO] no known issue with org.apache.maven.plugins:maven-site-plugin:3.12.1
[INFO] no known issue with org.apache.maven.plugins:maven-install-plugin:3.1.0
[INFO] no known issue with org.apache.maven.plugins:maven-deploy-plugin:2.8.2
[INFO]
[INFO] ---------------< org.apache.maven.doxia:doxia-sink-api >----------------
[INFO] Building Doxia :: Sink API 2.0.0-M5-SNAPSHOT                      [2/10]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-artifact-plugin:3.3.1-SNAPSHOT:check-buildplan (default-cli) @ doxia-sink-api ---
[INFO] no known issue with org.apache.maven.plugins:maven-enforcer-plugin:3.1.0
[INFO] no known issue with com.diffplug.spotless:spotless-maven-plugin:2.28.0
[INFO] no known issue with org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0
[INFO] no known issue with org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0 (>= 1.7.0)
[INFO] no known issue with org.apache.maven.plugins:maven-resources-plugin:3.3.0
[INFO] no known issue with org.apache.rat:apache-rat-plugin:0.15
[INFO] no known issue with org.apache.maven.plugins:maven-compiler-plugin:3.10.1
[INFO] no known issue with org.eclipse.sisu:sisu-maven-plugin:0.3.5 (>= 0.3.4)
[INFO] no known issue with org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7
[INFO] no known issue with org.apache.maven.plugins:maven-jar-plugin:3.3.0 (>= 3.2.0)
[INFO] no known issue with org.apache.maven.plugins:maven-site-plugin:3.12.1
[INFO] no known issue with org.apache.maven.plugins:maven-install-plugin:3.1.0
[INFO] no known issue with org.apache.maven.plugins:maven-deploy-plugin:2.8.2
[INFO]
[INFO] ---------------< org.apache.maven.doxia:doxia-test-docs >---------------
[INFO] Building Doxia :: Test Documents 2.0.0-M5-SNAPSHOT                [3/10]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-artifact-plugin:3.3.1-SNAPSHOT:check-buildplan (default-cli) @ doxia-test-docs ---
[INFO] no known issue with org.apache.maven.plugins:maven-enforcer-plugin:3.1.0
[INFO] no known issue with com.diffplug.spotless:spotless-maven-plugin:2.28.0
[INFO] no known issue with org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0
[INFO] no known issue with org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0 (>= 1.7.0)
[INFO] no known issue with org.apache.maven.plugins:maven-resources-plugin:3.3.0
[INFO] no known issue with org.apache.rat:apache-rat-plugin:0.15
[INFO] no known issue with org.apache.maven.plugins:maven-compiler-plugin:3.10.1
[INFO] no known issue with org.eclipse.sisu:sisu-maven-plugin:0.3.5 (>= 0.3.4)
[INFO] no known issue with org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7
[INFO] no known issue with org.apache.maven.plugins:maven-jar-plugin:3.3.0 (>= 3.2.0)
[INFO] no known issue with org.apache.maven.plugins:maven-site-plugin:3.12.1
[INFO] no known issue with org.apache.maven.plugins:maven-install-plugin:3.1.0
[INFO] no known issue with org.apache.maven.plugins:maven-deploy-plugin:2.8.2
[INFO]
[INFO] -----------------< org.apache.maven.doxia:doxia-core >------------------
[INFO] Building Doxia :: Core 2.0.0-M5-SNAPSHOT                          [4/10]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-artifact-plugin:3.3.1-SNAPSHOT:check-buildplan (default-cli) @ doxia-core ---
[INFO] no known issue with org.apache.maven.plugins:maven-enforcer-plugin:3.1.0
[INFO] no known issue with com.diffplug.spotless:spotless-maven-plugin:2.28.0
[INFO] no known issue with org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0
[INFO] no known issue with org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0 (>= 1.7.0)
[INFO] no known issue with org.apache.maven.plugins:maven-resources-plugin:3.3.0
[INFO] no known issue with org.apache.rat:apache-rat-plugin:0.15
[INFO] no known issue with org.apache.maven.plugins:maven-compiler-plugin:3.10.1
[INFO] no known issue with org.eclipse.sisu:sisu-maven-plugin:0.3.5 (>= 0.3.4)
[INFO] no known issue with org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7
[INFO] no known issue with org.apache.maven.plugins:maven-jar-plugin:3.3.0 (>= 3.2.0)
[INFO] no known issue with org.apache.maven.plugins:maven-site-plugin:3.12.1
[INFO] no known issue with org.apache.maven.plugins:maven-install-plugin:3.1.0
[INFO] no known issue with org.apache.maven.plugins:maven-deploy-plugin:2.8.2
[INFO]
[INFO] ----------------< org.apache.maven.doxia:doxia-modules >----------------
[INFO] Building Doxia :: Modules 2.0.0-M5-SNAPSHOT                       [5/10]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-artifact-plugin:3.3.1-SNAPSHOT:check-buildplan (default-cli) @ doxia-modules ---
[INFO] no known issue with org.apache.maven.plugins:maven-enforcer-plugin:3.1.0
[INFO] no known issue with com.diffplug.spotless:spotless-maven-plugin:2.28.0
[INFO] no known issue with org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0
[INFO] no known issue with org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0 (>= 1.7.0)
[INFO] no known issue with org.apache.rat:apache-rat-plugin:0.15
[INFO] no known issue with org.eclipse.sisu:sisu-maven-plugin:0.3.5 (>= 0.3.4)
[INFO] no known issue with org.apache.maven.plugins:maven-site-plugin:3.12.1
[INFO] no known issue with org.apache.maven.plugins:maven-install-plugin:3.1.0
[INFO] no known issue with org.apache.maven.plugins:maven-deploy-plugin:2.8.2
[INFO]
[INFO] --------------< org.apache.maven.doxia:doxia-module-apt >---------------
[INFO] Building Doxia :: APT Module 2.0.0-M5-SNAPSHOT                    [6/10]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-artifact-plugin:3.3.1-SNAPSHOT:check-buildplan (default-cli) @ doxia-module-apt ---
[INFO] no known issue with org.apache.maven.plugins:maven-enforcer-plugin:3.1.0
[INFO] no known issue with com.diffplug.spotless:spotless-maven-plugin:2.28.0
[INFO] no known issue with org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0
[INFO] no known issue with org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0 (>= 1.7.0)
[INFO] no known issue with org.apache.maven.plugins:maven-resources-plugin:3.3.0
[INFO] no known issue with org.apache.rat:apache-rat-plugin:0.15
[INFO] no known issue with org.apache.maven.plugins:maven-compiler-plugin:3.10.1
[INFO] no known issue with org.eclipse.sisu:sisu-maven-plugin:0.3.5 (>= 0.3.4)
[INFO] no known issue with org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7
[INFO] no known issue with org.apache.maven.plugins:maven-jar-plugin:3.3.0 (>= 3.2.0)
[INFO] no known issue with org.apache.maven.plugins:maven-site-plugin:3.12.1
[ERROR] plugin without solution org.springframework.boot:spring-boot-maven-plugin:3.0.2, see https://github.com/spring-projects/spring-boot/issues/21005
[INFO] no known issue with org.apache.maven.plugins:maven-install-plugin:3.1.0
[INFO] no known issue with org.apache.maven.plugins:maven-deploy-plugin:2.8.2
[INFO] current module pom.xml is C:\Entwicklung\Projekte\maven-doxia\doxia-modules\doxia-module-apt/pom.xml
[INFO]         parent pom.xml is C:\Entwicklung\Projekte\maven-doxia\doxia-modules/pom.xml
[INFO]         parent pom.xml is C:\Entwicklung\Projekte\maven-doxia/pom.xml
[INFO]
[INFO] --------------< org.apache.maven.doxia:doxia-module-fml >---------------
[INFO] Building Doxia :: FML Module 2.0.0-M5-SNAPSHOT                    [7/10]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-artifact-plugin:3.3.1-SNAPSHOT:check-buildplan (default-cli) @ doxia-module-fml ---
[INFO] no known issue with org.apache.maven.plugins:maven-enforcer-plugin:3.1.0
[INFO] no known issue with org.codehaus.modello:modello-maven-plugin:2.0.0
[INFO] no known issue with com.diffplug.spotless:spotless-maven-plugin:2.28.0
[INFO] no known issue with org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0
[INFO] no known issue with org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0 (>= 1.7.0)
[INFO] no known issue with org.apache.maven.plugins:maven-resources-plugin:3.3.0
[INFO] no known issue with org.apache.rat:apache-rat-plugin:0.15
[INFO] no known issue with org.apache.maven.plugins:maven-compiler-plugin:3.10.1
[INFO] no known issue with org.eclipse.sisu:sisu-maven-plugin:0.3.5 (>= 0.3.4)
[INFO] no known issue with org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7
[INFO] no known issue with org.apache.maven.plugins:maven-jar-plugin:3.3.0 (>= 3.2.0)
[INFO] no known issue with org.apache.maven.plugins:maven-site-plugin:3.12.1
[INFO] no known issue with org.apache.maven.plugins:maven-install-plugin:3.1.0
[INFO] no known issue with org.apache.maven.plugins:maven-deploy-plugin:2.8.2
[INFO]
[INFO] --------------< org.apache.maven.doxia:doxia-module-xdoc >--------------
[INFO] Building Doxia :: XDoc Module 2.0.0-M5-SNAPSHOT                   [8/10]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-artifact-plugin:3.3.1-SNAPSHOT:check-buildplan (default-cli) @ doxia-module-xdoc ---
[INFO] no known issue with org.apache.maven.plugins:maven-enforcer-plugin:3.1.0
[INFO] no known issue with com.diffplug.spotless:spotless-maven-plugin:2.28.0
[INFO] no known issue with org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0
[INFO] no known issue with org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0 (>= 1.7.0)
[INFO] no known issue with org.apache.maven.plugins:maven-resources-plugin:3.3.0
[INFO] no known issue with org.apache.rat:apache-rat-plugin:0.15
[INFO] no known issue with org.apache.maven.plugins:maven-compiler-plugin:3.10.1
[INFO] no known issue with org.eclipse.sisu:sisu-maven-plugin:0.3.5 (>= 0.3.4)
[INFO] no known issue with org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7
[INFO] no known issue with org.apache.maven.plugins:maven-jar-plugin:3.3.0 (>= 3.2.0)
[INFO] no known issue with org.apache.maven.plugins:maven-site-plugin:3.12.1
[INFO] no known issue with org.apache.maven.plugins:maven-install-plugin:3.1.0
[INFO] no known issue with org.apache.maven.plugins:maven-deploy-plugin:2.8.2
[INFO]
[INFO] -------------< org.apache.maven.doxia:doxia-module-xhtml5 >-------------
[INFO] Building Doxia :: XHTML5 Module 2.0.0-M5-SNAPSHOT                 [9/10]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-artifact-plugin:3.3.1-SNAPSHOT:check-buildplan (default-cli) @ doxia-module-xhtml5 ---
[INFO] no known issue with org.apache.maven.plugins:maven-enforcer-plugin:3.1.0
[INFO] no known issue with com.diffplug.spotless:spotless-maven-plugin:2.28.0
[INFO] no known issue with org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0
[INFO] no known issue with org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0 (>= 1.7.0)
[INFO] no known issue with org.apache.maven.plugins:maven-resources-plugin:3.3.0
[INFO] no known issue with org.apache.rat:apache-rat-plugin:0.15
[INFO] no known issue with org.apache.maven.plugins:maven-compiler-plugin:3.10.1
[INFO] no known issue with org.eclipse.sisu:sisu-maven-plugin:0.3.5 (>= 0.3.4)
[INFO] no known issue with org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7
[INFO] no known issue with org.apache.maven.plugins:maven-jar-plugin:3.3.0 (>= 3.2.0)
[INFO] no known issue with org.apache.maven.plugins:maven-site-plugin:3.12.1
[INFO] no known issue with org.apache.maven.plugins:maven-install-plugin:3.1.0
[INFO] no known issue with org.apache.maven.plugins:maven-deploy-plugin:2.8.2
[INFO]
[INFO] ------------< org.apache.maven.doxia:doxia-module-markdown >------------
[INFO] Building Doxia :: Markdown Module 2.0.0-M5-SNAPSHOT              [10/10]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-artifact-plugin:3.3.1-SNAPSHOT:check-buildplan (default-cli) @ doxia-module-markdown ---
[INFO] no known issue with org.apache.maven.plugins:maven-enforcer-plugin:3.1.0
[INFO] no known issue with com.diffplug.spotless:spotless-maven-plugin:2.28.0
[INFO] no known issue with org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0
[INFO] no known issue with org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0 (>= 1.7.0)
[INFO] no known issue with org.apache.maven.plugins:maven-resources-plugin:3.3.0
[INFO] no known issue with org.apache.rat:apache-rat-plugin:0.15
[INFO] no known issue with org.apache.maven.plugins:maven-compiler-plugin:3.10.1
[INFO] no known issue with org.eclipse.sisu:sisu-maven-plugin:0.3.5 (>= 0.3.4)
[INFO] no known issue with org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7
[INFO] no known issue with org.apache.maven.plugins:maven-jar-plugin:3.3.0 (>= 3.2.0)
[INFO] no known issue with org.apache.maven.plugins:maven-site-plugin:3.12.1
[INFO] no known issue with org.apache.maven.plugins:maven-install-plugin:3.1.0
[INFO] no known issue with org.apache.maven.plugins:maven-deploy-plugin:2.8.2
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Doxia 2.0.0-M5-SNAPSHOT:
[INFO]
[INFO] Doxia .............................................. SUCCESS [  1.125 s]
[INFO] Doxia :: Sink API .................................. SUCCESS [  0.085 s]
[INFO] Doxia :: Test Documents ............................ SUCCESS [  0.010 s]
[INFO] Doxia :: Core ...................................... SUCCESS [  0.025 s]
[INFO] Doxia :: Modules ................................... SUCCESS [  0.005 s]
[INFO] Doxia :: APT Module ................................ FAILURE [  0.025 s]
[INFO] Doxia :: FML Module ................................ SUCCESS [  0.050 s]
[INFO] Doxia :: XDoc Module ............................... SUCCESS [  0.010 s]
[INFO] Doxia :: XHTML5 Module ............................. SUCCESS [  0.005 s]
[INFO] Doxia :: Markdown Module ........................... SUCCESS [  0.010 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.975 s
[INFO] Finished at: 2023-02-03T15:13:03+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-artifact-plugin:3.3.1-SNAPSHOT:check-buildplan (default-cli) on project doxia-module-apt: non-reproducible plugin or configuration found with fix available -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :doxia-module-apt
PS C:\Entwicklung\Projekte\maven-doxia>
```

I believe this is acceptable and no further code is required in the plugin since `-fae` does the magic. @hboutemy WDYT?

**Comment by hboutemy** [comment]
nice idea, this `-fae`

**Comment by jira-importer** [comment]
Resolve #137

**Pull request closed without merging**
