### PR TITLE
Use slf4j-api for logging

### PR DESCRIPTION
**Pull request by slawekjaranowski**

### CODE REVIEW

**Review by bmarwell — CHANGES_REQUESTED** [review]
Please use the provided Log wrapper as it is. Maven ships slf4j.
If you use it explicitly, there is no way to migrate  the whole maven ecosystem.

Therefore my -1.
We already had the same discussion on the maven jlink plugin.

**Review by slachiewicz — APPROVED** [review]
+1 SLF4J is available for plugins from Maven 3.1 and it's fully supported

**Comment by slawekjaranowski** [comment]
@bmarwell can give me a link on the maven jlink plugin discussion ... and what was the result.

**Comment by bmarwell** [comment]
https://github.com/apache/maven-jlink-plugin/pull/23#issuecomment-740632700

@slachiewicz if you add your +1, you are ignoring the mailing list discussion and the discussion in slack.

By using our internal API, this plugin is already using slf4j. This this change will break migration to other frameworks in the future.

-1.

**Comment by slachiewicz** [comment]
Ok, -1

**Comment by slawekjaranowski** [comment]
There is inconsistent in this topic: 
https://issues.apache.org/jira/browse/MNG-6931
https://github.com/apache/maven/pull/385

**Comment by rmannibucau** [comment]
We can bring it back on the list if needed but mojo move never got validated afaik

**Pull request closed without merging**
