### PR TITLE
[MARTIFACT-62] Drop deprecated classes and artifacts

### PR DESCRIPTION
**Pull request by cstamas**
Just a general refresh: move off deprecated classes and artifacts.

---

https://issues.apache.org/jira/browse/MARTIFACT-62

### CODE REVIEW

**Comment by cstamas** [comment]
Ping @hboutemy @gnodet  any issue with this Pr?

**Comment by cstamas** [comment]
ASF Jenkins got "connection reset" :shrug:

**Comment by cstamas** [comment]
@hboutemy this should be merged ASAP

**Comment by hboutemy** [comment]
thank you @cstamas

**Comment by jira-importer** [comment]
Resolve #98

**Pull request merged**
